# Generated by Django 5.0.4 on 2024-05-13 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('color', models.CharField(max_length=6)),
                ('imagen', models.ImageField(upload_to='imagenes_proyectos/')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=16)),
                ('fecha', models.DateField()),
                ('imagen', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Apartado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=6)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='imagenes_apartados/')),
                ('id_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subapartados', to='CarDriveBk.apartado')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='proyecto',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario'),
        ),
        migrations.CreateModel(
            name='Proyectleader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_apartado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.apartado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Coordinador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_apartado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.apartado')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Archivados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.proyecto')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
    ]
