# Generated by Django 5.0.4 on 2024-05-23 17:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("CarDriveBk", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="usuarios",
            old_name="nombre",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="usuarios",
            name="last_name",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="usuarios",
            name="color",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9A-Fa-f]{6}$", "Enter a valid hex color code"
                    )
                ],
            ),
        ),
    ]
