# Generated by Django 5.0.4 on 2024-05-22 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDriveBk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiones',
            name='archivo',
            field=models.FileField(upload_to='documentos/'),
        ),
    ]
