# Generated by Django 5.0.4 on 2024-05-13 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDriveBk', '0002_etiquetas_archivos_asociar_etiquetas_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.archivos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Recientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField()),
                ('id_archivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.archivos')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarDriveBk.usuario')),
            ],
        ),
    ]
