# Generated by Django 5.0.4 on 2024-05-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDriveBk', '0002_alter_versiones_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiones',
            name='tamales',
            field=models.FileField(null=True, upload_to='documentos/'),
        ),
        migrations.AlterField(
            model_name='versiones',
            name='archivo',
            field=models.BinaryField(),
        ),
    ]
