# Generated by Django 5.0.4 on 2024-06-09 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDriveBk', '0003_alter_usuarios_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='versiones',
            name='nombre',
            field=models.TextField(default='primera iteracion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='archivos',
            name='fecha',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='relacionesetiquetas',
            name='id_archivos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relaciones_etiquetas', to='CarDriveBk.archivos'),
        ),
    ]
