# Generated by Django 5.0.4 on 2024-05-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarDriveBk', '0003_versiones_tamales_alter_versiones_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versiones',
            name='tamales',
        ),
    ]
